import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faDeleteLeft } from "@fortawesome/free-solid-svg-icons";

const keysBank = [
  {
    keyDisplayed: "AC",
    id: "clear",
    darkColor: "colors",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: <FontAwesomeIcon icon={faDeleteLeft} />,
    id: "clear-one",
    darkColor: "colors",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "%",
    id: "percentage",
    darkColor: "colors",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "÷",
    id: "divide",
    darkColor: "colors",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "7",
    id: "seven",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "8",
    id: "eight",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "9",
    id: "nine",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "x",
    id: "multiply",
    darkColor: "colors",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "4",
    id: "four",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "5",
    id: "five",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "6",
    id: "six",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "-",
    id: "substract",
    darkColor: "colors",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "1",
    id: "one",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "2",
    id: "two",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "3",
    id: "three",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "+",
    id: "add",
    darkColor: "colors",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "0",
    id: "zero",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: ".",
    id: "decimal",
    darkColor: "",
    keyStyleCol: "col p-0 mb-2 me-2",
    keyStyleBtn: "btn-secondary w-100 buttons-size",
  },
  {
    keyDisplayed: "=",
    id: "equals",
    darkColor: "",
    keyStyleCol: "col-6 p-0",
    keyStyleBtn: "equals-width",
  },
];

export default keysBank;
